### ISSUE TITLE
Encrypt only the Settings from the current Environment

### ISSUE THREAD

**Issue by skelso01** [ChustaSoft/SecureConfig#46]
We use the ASPDOTNETCORE_EVIRONMENT mechanism, so we have a separate AppSetting per environment (AppSettings.development.json, AppSettings.Production.json, ...) Now when I am in the development environment, it should be possible that only the settings of the development environment are encrypted. 
At the moment the solution encrypts all appsettings.*.json files and in this case writes the wrong string to other appsettings.

Example:
I have AppSettings.dev.json, AppSettings.prod.json, in each of which environment relevant connection string is stored. If I now use this solution, the encryption mechanism writes one of the two connection strings encrypted into both AppSettings. So that we have here no more difference in the different AppSettings.

I use this solution in .netcore 3.1

**Comment by xaberue** [comment]
Hi @skelso01 ,

Thanks for reporting the issue, we can investigate further.

Best regards

**Comment by xaberue** [comment]
Hi @skelso01 !!!

We found and fixed the issue.

When decrypting and encrypting, it was incorrectly managing it from the configuration instead of retrieving the correct json.

The fix has been done and released, **version 1.4.2** of the package should fix your issue.

Thank you once again for reporting the bug  :) 

Regards

**Comment by skelso01** [comment]
Hi @Xelit3
Incredibly fast response. Thank you very much. It now works exactly as expected.

Best regards
