### ISSUE TITLE
Encryption working with XML app.settings?

### ISSUE THREAD

**Issue by Akitektuo** [ChustaSoft/SecureConfig#50]
Hello, 

We have an. ...interesting... project and we have to use app.settings in XML format instead of JSON. I followed all the steps from the video, documentation and .net 6 example. The code compiles fine, the settings are injected into the service properly (the properties have the expected values), but the app.settings.xml remains unchanged.

I want to encrypt ServerUser from below:
```
<?xml version="1.0" encoding="utf-8" ?>
<AppConfiguration>
...
  <ServerUser>
    <Username>test</Username>
    <Password>test</Password>
  </ServerUser>
...
</AppConfiguration>
```
Of course, I also specified the custom tag `ServerUser` and when trying to obtain `configuration["ServerUser:Username"]` the correct value is received.

Do you know if the XML format is at fault for not replacing the Username and Password?

**Comment by xaberue** [comment]
Hi @Akitektuo !!

Despite that I know that using Microsoft.Extensions.Configuration.Xml it's possible to manage settings in ASP.NET Core using xml format, I'm afraid that the tool is only supporting the default and more widespread JSON format.

I imagine that when the tool is trying to find the different *.json files is not able to retrieve anything and then is not encrypting any value, but since the provider can load the settings from the file, is loaded with normality.

I strongly recommend to use JSON settings instead, however how the tool is done, should not be extremly complicated to add support to XML providers, so pull requests are always welcomed.

Sorry if the tool doesn't fit currently this requirements, I hope to have clarified the doubt.

Best regards

**Comment by Akitektuo** [comment]
Hi @Xelit3,

Thank you for the reply. Indeed, I went over the library's files and now it makes sense the way someone would use the library. In the end, we got inspired by the source code and we implemented our version for XML which doesn't map to a POJO. 

The usage is different, instead of mapping an object, you directly specify the properties you want encrypted eg: .Encrypt("ServerUser:Username", "ServerUser:Password"). We used your Encryption helper which was very handy and easy to use, so thank you a lot for that. If someone needs our way of implementing this I could make the code public, but I wouldn't modify this library since I am not sure how mapping a POJO to XML works.

So thank you again for having this library and its source code, it really helped us!
On my part, this could be closed.

**Comment by xaberue** [comment]
Hi @Akitektuo !!

Thanks for your reply, and sorry for the delay in mine...

I'm glad to see that the tool helped somehow, and I'll be glad to assist improving this tool with your own requirement. 
I'm a strong defensor of the open source philosophy where everybody can be benefited from other's contribution, so given that premise, may I ask to commit these changes too following the same philosphy with which this tool was born?

With your requirements, changes and my knowledge on the tool and support we can create newer and valid contibutions to the community.

Please let me know you thoughts about it.

Best regads

**Comment by xaberue** [comment]
Closing the issue since seems that no more actions will be done
